
import pandas as pd

###
start_train = pd.Timestamp('2019-05-06') # inklusive
ende_train  = pd.Timestamp('2020-05-05') # inklusive
start_test  = pd.Timestamp('2020-05-06') # inklusive
ende_test   = pd.Timestamp('2021-05-05') # inklusive
datum_min   = start_train-pd.Timedelta('365d') # inklusive

###
dict_rename = {'ARTIKELNR':'Artnr',
               'WARENGRUPPENINDEX':'WGidx',
               'HAUPTWARENGRUPPE':'HWG',
               'UNTERWARENGRUPPE':'UWG',
               'LADENPREIS':'Preis',
               'AUTOR':'Autor',
               'TITEL':'Titel',
               'TITELART':'Titelart',
               'SCHLAGWORT':'Schlagwort',
               'HAUPTSCHLAGWORT':'Hauptschlagwort',
               'ERSCHEINUNGSJAHR':'Erscheinungsjahr',
               'DATUMSWERT':'Datum',
               'BEDARF':'Bedarf',
              }
###
dict_WGidx = {0:'keine Warengruppe',
              1:'Hardcover, Softcover, Karte',
              2:'Taschenbuch',
              3:'Loseblatt, Zeitschrift',
              4:'Video, DVD-Video',
              5:'Audio-CD, Cassette',
              6:'CD-ROM, DVD-ROM, Diskette',
              7:'Kalender',
              8:'Nonbook, PBS',
              9:'Modernes Antiquariat'}
###
dict_HWG = {0:'keine Hauptwarengruppe',
            1:'Belletristik',
            2:'Kinder- und Jugendbuch',
            3:'Reise',
            4:'Sachbuch/ Ratgeber',
            5:'Geisteswissenschaften, Kunst und Musik',
            6:'Mathematik, Naturwissenschaft und Technik',
            7:'Sozialwissenschaften, Recht und Wirtschaft',
            8:'Schule und Lernen',
            9:'Freibereich'}
###
dict_UWG = { 0:'keine Unterwarengruppe',
             1:'frei',
            10:'frei',
            11:'Belletristik - Romane, Erzählungen und Anthologien',
            12:'Belletristik - Krimis',
            13:'Belletristik - Science Fiction und Fantasy',
            14:'Belletristik - Märchen und Sagen',
            15:'Belletristik - Lyrik, Dramatik, Essays',
            16:'Belletristik - Briefe, Tagebücher, Biografien, Autobiografien',
            17:'Belletristik - Fremdsprachige Literatur',
            18:'Belletristik - Humor, Cartoons, Comics, Satire',
            19:'Belletristik - Geschenkbücher',
            20:'frei',
            21:'Kinder- und Jugendbuch - Bilderbücher',
            22:'Kinder- und Jugendbuch - Sachbilderbücher',
            23:'Kinder- und Jugendbuch - Geschichten, Reime, Lieder',
            24:'b',
            25:'Kinder- und Jugendbuch - Romane und Erzählungen',
            26:'Kinder- und Jugendbuch - Märchen und Sagen',
            27:'Kinder- und Jugendbuch - Tiergeschichten',
            28:'Kinder- und Jugendbuch - Sachbücher ',
            29:'Kinder- und Jugendbuch - Spielen und Lernen ',
            30:'frei',
            31:'Reise - Reiseführer ',
            32:'Reise - Sport- und Aktivreise ',
            33:'Reise - Hotel- und Restaurantführer ',
            34:'Reise - Karten, Stadtpläne, Atlanten  ',
            35:'Reise - Bildbände ',
            36:'Reise - Reiseberichte und Erzählungen ',
            37:'Atlanten',
            38:'Reise - Globen ',
            39:'Reise - Kartenzubehör und Sonstiges ',
            40:'frei',
            41:'Sachbuch/ Ratgeber - Nachschlagewerke ',
            42:'Sachbuch/ Ratgeber - Hobby, Freizeit, Natur ',
            43:'Sachbuch/ Ratgeber - Fahrzeuge, Flugzeuge, Schiffe ',
            44:'Sachbuch/ Ratgeber - Sport ',
            45:'Sachbuch/ Ratgeber - Essen und Trinken ',
            46:'Sachbuch/ Ratgeber - Gesundheit und Körperpflege ',
            47:'Sachbuch/ Ratgeber - Esoterik und Anthroposophie ',
            48:'Sachbuch/ Ratgeber - Ratgeber ',
            49:'Sachbuch/ Ratgeber - Sonstiges ',
            50:'frei',
            51:'Geisteswissenschaften, Kunst und Musik - Geisteswissenschaften ',
            52:'Geisteswissenschaften, Kunst und Musik - Philosophie ',
            53:'Geisteswissenschaften, Kunst und Musik - Psychologie ',
            54:'Geisteswissenschaften, Kunst und Musik - Religion und Theologie ',
            55:'Geisteswissenschaften, Kunst und Musik - Geschichte ',
            56:'Geisteswissenschaften, Kunst und Musik - Sprachwissenschaft ',
            57:'Geisteswissenschaften, Kunst und Musik - Literaturwissenschaft ',
            58:'Geisteswissenschaften, Kunst und Musik - Kunst ',
            59:'Geisteswissenschaften, Kunst und Musik - Musik ',
            60:'frei',
            61:'Mathematik, Naturwissenschaft und Technik - Naturwissenschaften ',
            62:'Mathematik, Naturwissenschaft und Technik - Mathematik ',
            63:'Mathematik, Naturwissenschaft und Technik - Informatik und EDV ',
            64:'Mathematik, Naturwissenschaft und Technik - Physik und Astronomie ',
            65:'Mathematik, Naturwissenschaft und Technik - Chemie ',
            66:'Mathematik, Naturwissenschaft und Technik - Geowissenschaften ',
            67:'Mathematik, Naturwissenschaft und Technik - Biologie ',
            68:'Mathematik, Naturwissenschaft und Technik - Technik ',
            69:'Mathematik, Naturwissenschaft und Technik - Medizin und Pharmazie ',
            70:'frei',
            71:'Sozialwissenschaften, Recht und Wirtschaft - Sozialwissenschaften ',
            72:'Sozialwissenschaften, Recht und Wirtschaft - Pädagogik ',
            73:'Sozialwissenschaften, Recht und Wirtschaft - Medien und Kommunikation ',
            74:'Sozialwissenschaften, Recht und Wirtschaft - Politik, Gesellschaft, Arbeit ',
            75:'Sozialwissenschaften, Recht und Wirtschaft - Völkerkunde und Volkskunde ',
            76:'Sozialwissenschaften, Recht und Wirtschaft - Umwelt, Land- und Forstwirtschaft ',
            77:'Sozialwissenschaften, Recht und Wirtschaft - Recht ',
            78:'Sozialwissenschaften, Recht und Wirtschaft - Wirtschaft ',
            79:'frei',
            80:'frei',
            81:'Schule und Lernen - Schulbücher',
            82:'Schule und Lernen - Unterrichtsmaterialien',
            83:'Schule und Lernen - Berufs- und Fachschulbücher',
            84:'Schule und Lernen - Lernhilfen und Abiturwissen',
            85:'Schule und Lernen - Lektüren und Interpretationen',
            86:'Schule und Lernen - Erwachsenenbildung und VHS',
            87:'Schule und Lernen - Deutsch als Fremdsprache',
            88:'Schule und Lernen - Lernsoftware ',
            89:'Schule und Lernen - Sonstiges',
            90:'frei',
            99:'frei'}

###
dict_dtypes = {'Artnr'       :'int32',
               'WGidx'       :'int8',
               'UWG'         :'int8',
               'Preis'       :'float32',
               'Alter'       :'int16',
               'Bedarf'      :'int16',
               'sum_Bedarf'  :'int32',
               'last_Bedarf' :'int16',
               'cnt_Best'    :'int16',
               'passed'      :'int16',
               # 'Monat'       :'int8',
               # 'KaWo'        :'int8',
               # 'WoTa'        :'int8',
              }

